import Head from "next/head";

import { Container, VStack } from "@chakra-ui/react";

import Header from "../components/Header";
import Footer from "../components/Footer";
import TopBanner from "../components/TopBanner";
import TopProducts from "../components/TopProducts";
import TopCategories from "../components/TopCategories";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Container maxW="1204px" pt="100px">
        <VStack spacing={10}>
          <TopBanner />
          <TopProducts />
          <TopCategories />
          <TopProducts />
          <TopCategories />
        </VStack>
      </Container>

      <Footer />
    </div>
  );
}
