import Head from "next/head";

import Header from "../components/Header";
import Footer from "../components/Footer";
import TopBanner from "../components/TopBanner";
import TopProducts from "../components/TopProducts";
import TopCategories from "../components/TopCategories";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="max-w-5xl pb-4 m-auto pt-28">
        <div className="space-y-6">
          <TopBanner />
          <TopProducts />
          <TopCategories />
          <TopProducts />
          <TopCategories />
        </div>
      </div>

      <Footer />
    </div>
  );
}
